..E
======================================================================
ERROR: test_ten (test_numbers.NumbersTest.test_ten)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 44, in test_ten
    result = str(Numbers().to_number(10))
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 6, in to_number
    return self.digits[number]
           ~~~~~~~~~~~^^^^^^^^
IndexError: list index out of range

----------------------------------------------------------------------
Ran 3 tests in 0.016s

FAILED (errors=1)
