.E...EE..EE
======================================================================
ERROR: test_every_three_digit_number (test_numbers.NumbersTest.test_every_three_digit_number)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 63, in test_every_three_digit_number
    result = [Numbers().to_number(number) for number in range(100,1000)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 36, in to_number
    array_of_numbers_by_order = self.disect_number(number)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 84, in disect_number
    array_of_ordered_numbers.append(int(str(number)[start:end]))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

======================================================================
ERROR: test_one_hundred (test_numbers.NumbersTest.test_one_hundred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 51, in test_one_hundred
    result = Numbers().to_number(100)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 36, in to_number
    array_of_numbers_by_order = self.disect_number(number)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 84, in disect_number
    array_of_ordered_numbers.append(int(str(number)[start:end]))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

======================================================================
ERROR: test_one_thousand_five_hundred_and_one (test_numbers.NumbersTest.test_one_thousand_five_hundred_and_one)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 68, in test_one_thousand_five_hundred_and_one
    verify(result)
  File "/usr/local/lib/python3.12/site-packages/approvaltests/approvals.py", line 120, in verify
    verify_with_namer(
  File "/usr/local/lib/python3.12/site-packages/approvaltests/approvals.py", line 220, in verify_with_namer
    verify_with_namer_and_writer(namer, writer, options=options)
  File "/usr/local/lib/python3.12/site-packages/approvaltests/approvals.py", line 231, in verify_with_namer_and_writer
    error = FileApprover.verify(namer, writer, options.reporter, options.comparator)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/approvaltests/file_approver.py", line 55, in verify
    verified = FileApprover.verify_files(approved, received, reporter, comparator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/approvaltests/file_approver.py", line 111, in verify_files
    raise ReporterNotWorkingException(reporter)
approvaltests.file_approver.ReporterNotWorkingException: Reporter <approvaltests.reporters.report_on_cyber_dojo.ReportOnCyberDojo object at 0x7f42d87293d0> failed to work!

======================================================================
ERROR: test_three_hundred (test_numbers.NumbersTest.test_three_hundred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 55, in test_three_hundred
    result = Numbers().to_number(300)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 36, in to_number
    array_of_numbers_by_order = self.disect_number(number)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 84, in disect_number
    array_of_ordered_numbers.append(int(str(number)[start:end]))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

======================================================================
ERROR: test_three_hundred_ten (test_numbers.NumbersTest.test_three_hundred_ten)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 59, in test_three_hundred_ten
    result = Numbers().to_number(310)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 36, in to_number
    array_of_numbers_by_order = self.disect_number(number)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 84, in disect_number
    array_of_ordered_numbers.append(int(str(number)[start:end]))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

----------------------------------------------------------------------
Ran 11 tests in 0.029s

FAILED (errors=5)
